export const REGISTERED_SUCCESSFULLY = 'REGISTERED_SUCCESSFULLY';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const LOGGED_IN_SUCCESSFULLY = 'LOGGED_IN_SUCCESSFULLY';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGGED_OUT = 'LOGGED_OUT';

export const LOGIN_BTN_CLICK = 'LOGIN_BTN_CLICK';
export const REGISTER_BTN_CLICK = 'REGISTER_BTN_CLICK';

export const LOGIN_FIELD_CHANGE = 'LOGIN_FIELD_CHANGE';
export const PASSWORD_FIELD_CHANGE = 'PASSWORD_FIELD_CHANGE';